const POS_LABELS_PT_BR: Record<string, string> = {
  n: 'Substantivo',
  ni: 'Substantivo (í)',
  npr: 'Nome próprio',
  v1: 'Verbo (ichidan)',
  v5: 'Verbo (godan)',
  vk: 'Verbo (kuru)',
  vs: 'Verbo suru',
  vt: 'Verbo transitivo',
  vi: 'Verbo intransitivo',
  adj: 'Adjetivo',
  'adj-i': 'Adjetivo (í)',
  'adj-na': 'Adjetivo na',
  'adj-no': 'Adjetivo no',
  'adj-t': 'Adjetivo tari',
  adv: 'Advérbio',
  'adv-to': 'Advérbio (to)',
  aux: 'Auxiliar',
  'aux-v': 'Verbo auxiliar',
  'aux-adj': 'Adjetivo auxiliar',
  conj: 'Conjunção',
  int: 'Interjeição',
  num: 'Numeral',
  pref: 'Prefixo',
  suf: 'Sufixo',
  exp: 'Expressão',
  ic: 'Caractere isolado',
  prt: 'Partícula',
  ctr: 'Contador',
  demonstr: 'Demonstrativo',
  cop: 'Cópula',
  quant: 'Quantificador',
  unc: 'Não classificável',
  myth: 'Figura mitológica',
};

export function localizePos(pos: string): string {
  return POS_LABELS_PT_BR[pos] ?? pos;
}
